### ISSUE TITLE
Not able to load configuration

### ISSUE THREAD

**Issue by Marlock1234** [ghorint2t/scripts#16]
I get this message: "This is not a valid grid configuration file: wrong subfilter for os".

Help please.

**Comment by ghorint2t** [comment]
Apparently your save file somehow contained a wrong value for the filter. Not sure how could that happen; perhaps I've accidentally changed format at some point and the file was from an older version. Anyway, I've changed configuration restoration to simply ignore broken filter etc. entries rather than fail entirely on them. This should fix the problem for you (although perhaps some filters may not be restored as you saved them).

**Comment by Marlock1234** [comment]
Hi there. Unfortunately, I still get the same error. I have saved configuration, tried to load, but I get the same message.

**Comment by Marlock1234** [comment]
Hi there. Unfortunately, I still get the same error. I have saved
configuration, tried to load, but I get the same message.

pon, 11. srp 2022. u 03:18 ghorint2t ***@***.***> napisao je:

**Comment by Marlock1234** [comment]
SCRATCH THAT - I have updated the script and it works again :) Many thanks!

**Comment by Marlock1234** [comment]
SCRATCH THAT - I have updated the script and it works again :) Many thanks!

pon, 11. srp 2022. u 10:41 Lord Marlock ***@***.***> napisao
je:
